name: train-model
on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs for training'
        required: true
        default: '1'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Docker action
        id: train
        uses: ./train-action/
        with:
          epochs: 1

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: model.keras

