name: train-model
on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs for training'
        required: true
        default: '1'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Train in docker
        id: train
        uses: ./
        with:
          epochs: "${{ github.event.inputs.epochs }}"

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: model.keras

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: model

      - name: Test in docker
        id: train
        uses: ./
        with:
          epochs: "${{ github.event.inputs.epochs }}"


  ensure-model-size:
    name: "Ensure model size"
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: model

      - name: Check model size
        run: "du -h model.keras"

